os:
  - linux
  - osx
dist: trusty
sudo: required
language: node_js
matrix:
  include:
  - node_js: '0.11'
    env: AMBIENTE=local
  - node_js: '5.11'
    env: AMBIENTE=local
  - node_js: '6'
    env: AMBIENTE=heroku
  - node_js: '6.1'
    env: AMBIENTE=heroku
  allow_failures:
  - os: osx
    node_js: '6.1'
    env: AMBIENTE=local
branches:
  only:
  - master
  - stable
before_install:
  - docker build -f Dockerfile -t $REPO:$COMMIT .
services:
  - docker
env:
  global:
  - secure: uughg97HKBYLzaZ6qdvQwdWZQujFwwKKIyGdHOGf6Cp+ZAybAyu3SrFAjBIEadVIAZLNeYeZ3oWasJ63+hgBDfH/pwsb/MYNAmWhe9fogN3RdT0/eveZnu+DBCU3XAH8UmzkCjQElNFJkIIBKVNK+7Wi8lW91q4+0XE/hUTzz7l7i6H3D2XxLeI40ENePSAYCOL1LTpMNQzJJFFdqgygwXJDx9cDuhMOea+PgBTO5K4OTP0cXPiZu7Ni+3Af6l7P1jMt79isnEagL0s08IRlVu1G0aSReHeNGx8Yzpa5kPi+xJcrrNY84n/BfnCy9dBfuKpjm1yEu/0ZbdVSxdxRW1l38yfn77R2NJWz3WcF3XtKMthNpuhTXEApon3qhM9avarE5mzNFGCFahJ0Jydvs1dElg1Z020YZfsf/dY+TLKVN8LzmzV32X83z3z6FFpaFjd/9biPkIEFm6r+2jahcSTbvOpd04f3LyJWMhAcV4ExQg47BtDnhd7VYLAX6akJMFFEcFZi6DciHkCJ/c2be3x6x2s5s9tXBI0T8b6NpTvJ8JFSu7I0ow0zHm54yzfEKmUi6YGXeks8fxHZMNEz5UDKBEo+OgYGdxyVd1oEPYaMzyfE5DN5xsIqIzeJ/RSMKTa6kQ3TKdVLTEIa4V5r1V7sH3R0+a4f1dqbsSaAQ4I=
  - secure: qJOE4dxXz2ipfQIorGu5btlYNq9itcwuMxQIpiQqnGjNQblpV8e1GoEzSi84NI8UQvpb9e1/h7vJ+Ovph1n2fSDsfVFpuCV0x++UOkZJ/+2LB26+KK1QxE7TYnv3TejKaPzIU1L+PoA6lWSUp4hYgheiBOCh+mYPiqfH8qT5wRgGXDCRrlHGwx0QBLN3dire0GVJj94hgOgpt4mGSDOg1XQRdLpIqYn43SEinhzvj+UOrbXiQwUDqnGTmFjTDMOxT4KJfAyYVKwSNDhCm1xXbQ17LZaWKZ4/tNGQaUQpyd7HgYjW53h2vfxcVVnPTvtfI+t+pVae1ESQMuePjZOQaCo2BSi8xIZyZLKnCXBqcBXLShDh9Dyx1xumF1EoPARLWrYSc/WAK1iF7W4pVwGyoi90kH7A+fDQ6zIHW83ePF4gP0zsesMcnw6Rj2PaH/qWxDWm+1EfUUtWXukwccmYh5sRICG+UV8+4nlpsfDePSSW2QjJKPUQOt65w4CH1by26uMg6mwsC1XcEYzWaSNCHKeWsCXghgvAIU25LUAVDzFiJxP2t2dJ8y8n2iUwumsMtiLhxXp024F3AqtWa9020IabBBXIOt1BA0F6HG9kvofe1aroZSM8YzkEzMJWOcbBTpl6G6PlmoGvHoLEpIkKTKkLGjLS8F2hjI73OrFefHs=
  - secure: uPWk94yY/1WM72sPC9xVvYpWZ4eRu4FKZapu3SetmPRBV/pCpmWWFuALmWUqTYP1umQ5nJK0e+htqeUF0lhaHUUotbkT60o6pgrWaeFW4yyHMYUnKU740qFWPgMvxgGoK5u5nj5sOHp9VQr9RfXeBJwiGznztwdHG2aQfmy19UFRe8CnURuJzaEqpesvMiWtP4RtDwH7PoNxfPGzm6BFjvhKgOSokqX26HDjTcnv51pkSvadHhKYSzXf0C5IBNjze/4YE5QzTxlv/bBEGKtJGLwv7JuOhV2XXoKG5pzaVmex+JkOLw7lSex3AOKl5NbsiEO+nwVevOnQFpW74BWm3XqBDUl3KQW2FarBUPjmAxOHxum7fA1fDYzwIyedwjiKAi64SBtxe5A1zytF8fCRAYxZ5d8y0S5V0ZpfKwsJx1+/sI4boebFMw5P9rjkRXwQYmw4v6iyFJOSxUZ3VqSl9AKywDAqPfVZX/KUzs9qSyksePc3wTUHRFMzquC4Xz/XspYJhQXE8UnXtRkYedQ1i68dDQoVRkPjQvYbhJruc6m0mVgYMt8V+cs3efeIahqcSkHFtzHLcq/CBakbnMzWXnNacx7/Nn5c8SPaWSpsqCUdgCP7PCw6rnFeZ2J4T2hRC5Yc0AI2LvCS/9suhXt86piE+13Vb1ZwVZjYwtN75Pw=
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=camillagds/memory-game
  - secure: Sqs9Luidh1NYsob3lDh23FSpyC84Dg6Q2eTVDSqKAL/WjR6x5gDksl46MsVRmDzmIH6ouFcr6jXEPszsbQJbRmZp/t9AbOd4J58XpCe89ag2gpJtduu01BpGnLmmgw7i81vuDx+cvjt3a5IyEIgbfwou8in7puWT+nNdb4roMlBP/C5E/Vo6p3+Fcn9rgwQCpZaolKO4iHAYlbcOFjU8tWaJDjySgAT0VOpcu9bXnll+hRz8aM8zxe39kw5QQfxZSV06w5F20+2X5McNBEeCICVuEkF7DhuaBwd44939T9HJ98VhlafaMDPAytLyPD41v5ytWLU13BcwoKywcwEYyraWcXpThZVgND6WtvWXBwbmWCPA7GuMXp2rEdpJB+x0a9r4b9ctqQRElNWqA1hbK2MrDf2Gz7pAD7/pimrde3KTJCCLqy2GTanBt/6cpeGm4/g+WqIbDNovXw+m4EVZap6vD637D49VD7Ru4y5o36WVaVeP/a3onhsKVMC/DMyfSJN0AekKvhV6+YBRHwm/3CiaihepdKZfAtD4zFfufpBCZncXnKKZpBBWRx4PR9PyVYZjmCvlw60olOLzL/RYvnMwZ/SgqA7xmypfihzeqnrWA1ZK4gXWd4mH/JID9Ld9IOeefvoAc5BFGzXVQqAglLZyAE4SWNTXSpsiBIeAmIw=
  - secure: Amia1Tvhi0RmYS27b6cJ23m8A/NJ6bSom0bMSVZEfbLLytUI4jMv0aNp8M4aFS8Dku+PKMvIbGVTXeSgTlWbjLWOVHGtbxfUpG6EGPzHDKlsmY5pNlmiXg6m1/iVflXpe6sh0SP6h5e1ChsxE2zlF/t0D6YzvTyMg2y68hqpSIwUtPEIyD5hQPlsEtyG2PD9H4l8qYFJqz7VvIMWzrK9obo17pzUfTKuK+NFuKY4HX5jtLfct/XV8pL+mGlaLBk+weXHNtzngw+luFBbksz8PXMZRCe/aGBB8Kafz7pXefQ+6WbRAHRjHdunYXbsEdN18Q+xVL7nIB29prPIiKEadc7M61zZYyiub1bPtZEOvQns9R40DJJtPN9jyRSI4kooiX/L4A87z9oH/KpCXfcpd1hYTqogbxVJJLUdbKo23AXsCybmqTEse60IAPuWLh5rwZCfKU0BP6dpl1+TL82pXgOJmqAw5pJWJhaxxQiviVUiFKjRdqOE4g9W7gH1eUNfWJIp/smEX5Ic3HwEBZ674OinkXMADonXC5hy0rAVWxlo1Og8wxJr5cxLH3FmR4jQjK9FRDL3cVLo3y/wBx7WAwmMGwHELS1hpeCfe2eOCau8qH0INf51l6xQgwPgIDsY4taDxMSFF8t2G3dQvnmmo/Y6t39iLmtSIj3dVpINoUs=
install:
  - npm install -g forever
  - npm install

script:
  - docker run -d --name app -p 8080:8080 $REPO:$COMMIT
  - sleep 5 && docker ps -a | grep app
  - curl -l http://127.0.0.1:8080
  - docker exec -d app chmod +x /usr/src/app/test_app.sh
  - docker exec -d app sh /usr/src/app/test_app.sh
after_script:
  - docker rm -f app
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - mkdir out && zip -r out/memory-game_$TRAVIS_BUILD_NUMBER.zip . -x .* .sh .yml Dockerfile
  - sh set_tags.sh
  - export DEPLOY=SIM
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: 17Qe+TsokuAvgDRa2kLs03QyA06Lu+PlWD87L5Tjr6rp8wtXEPmOUNj0YYKjw4KEYITYFe62y9+UKhPJ8Bze68RHa03BwRicCZkDW5aw9vfPYCyj0ENnIbV1R4BvPuLeM80LrljU75TYpw2mW8t4Q2Of2TBzkYAGX0m1x+1jyOGZsjRx7tvVu69psDXIfkGsWfcUn3zRmp6oyg+6FUU4h5hz/U31tcU/+Oow9gSv7BqxjkMKBGDVSBn5KZMidswD77BNu4gnAMjtsukTqX9Eo+pdq4OY7baPp75Il4D3BE7LaW0NS/jK3+SMruQOLxyYjUfd2jIuPoPH8mQxhc7UTQaVa1p7lB8xlkpjJqw5iy81xhs5H8pLfD7PeutzVCGf8ayXVxHXyN3q1qgWqkspBDSAR7rRZDmo5muowC1rovPbCW39RaGOjk0yzM3FAhuQIVjfHoVja7NytVkl3kSFfODX+pC0WA9qkBBoAUZv9jh3TbHaFt+bVYfFy88oBcXuaQJzcbCn1pPNumDMyNVJHOLXaNGpmkqzmJ30aMZzjljJeDn6aktU8U9B+gniy1ZS348ZlaStjMjXKgqjpDO1aZpRvhJvS0hZu7YLZspEZ8aFj7luBMdtB9dQpRDaiYSjl21ex6m9SsZI4TxlYbM48tz7vyIDOuQDrtBnpbsxLHg=
    app: memory-game-staging-lobinhaxd
    on:
        repo: camillagds/Memory-Game
        branch: master
        condition: "$AMBIENTE = heroku"
        node: '6.1'
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: 17Qe+TsokuAvgDRa2kLs03QyA06Lu+PlWD87L5Tjr6rp8wtXEPmOUNj0YYKjw4KEYITYFe62y9+UKhPJ8Bze68RHa03BwRicCZkDW5aw9vfPYCyj0ENnIbV1R4BvPuLeM80LrljU75TYpw2mW8t4Q2Of2TBzkYAGX0m1x+1jyOGZsjRx7tvVu69psDXIfkGsWfcUn3zRmp6oyg+6FUU4h5hz/U31tcU/+Oow9gSv7BqxjkMKBGDVSBn5KZMidswD77BNu4gnAMjtsukTqX9Eo+pdq4OY7baPp75Il4D3BE7LaW0NS/jK3+SMruQOLxyYjUfd2jIuPoPH8mQxhc7UTQaVa1p7lB8xlkpjJqw5iy81xhs5H8pLfD7PeutzVCGf8ayXVxHXyN3q1qgWqkspBDSAR7rRZDmo5muowC1rovPbCW39RaGOjk0yzM3FAhuQIVjfHoVja7NytVkl3kSFfODX+pC0WA9qkBBoAUZv9jh3TbHaFt+bVYfFy88oBcXuaQJzcbCn1pPNumDMyNVJHOLXaNGpmkqzmJ30aMZzjljJeDn6aktU8U9B+gniy1ZS348ZlaStjMjXKgqjpDO1aZpRvhJvS0hZu7YLZspEZ8aFj7luBMdtB9dQpRDaiYSjl21ex6m9SsZI4TxlYbM48tz7vyIDOuQDrtBnpbsxLHg=
    app: memory-game-lobinhaxd
    on:
        repo: camillagds/Memory-Game
        branch: stable
        condition: "$AMBIENTE = heroku"
        node: '6.0'
  - provider: releases
    skip_cleanup: true
    api_key: 
      secure: Xk6gST7HRN5u6LoYwv2IeVhd4yqjZ7vDJMB4IBns86AQfPBbZTfv8MXx1rzAGrckS901kuSwMy9rJP8XmiV0WhXxKost5aqHhGce0TZMxfZZwfLJnXIJ/0Yd9OjMWFcyge5w4uEKVTP3qXOCkmkmPzpgOLhRMyAgknA9lOHePcDo2loB0hsluallH/NiB9O38RcDbl/C9kf/AHi9CTELT605MnNr99DwkNBFpAa7tVP4611Pl42dXDe7mI6YSjxGHhQWoM+oxr9POoVfvbMRU6REtiNJxwokqIK6UbhQVQfHW/DVloe94yayYhIQ8MRqpMJXwiHgbDpRuxpyJB37J6lnVqXDublBhcVL9XjP+K0dbOKDtDiKY/iBZkJQ9Wb80FynzlV6rZIZ6DBZgHTz3R/jPokhti0jrBtM4aUoSu2Kb+Ak02CkNZ8EOUHqy+z0RMqUzTxobetISyqHkeyXlA11P39mKij8bwpbZiTdAWCPz9lhEWieHJn4kH9VNTl1WafEYSTe9vmqgNEf/B3rcwJiwKR9uCMyoKaJYTyD/4+Q4F7OQ7XRC8JyqERnUHDjEvsSkcqMcLKDDDIvfnBY7qMgQTSTv2/JbSK4C3DETpq2kgWbMXgjLjf2yaORygB6F4XHd8m7QqsD09gXOOJpvyVYTBGfH80O3DjOu1IMN5A=
    file: "out/memory-game_$TRAVIS_BUILD_NUMBER.zip"
    on:
        repo: camillagds/Memory-Game
        branch: stable
        condition: "$AMBIENTE = ARRUMAR A CHAVE"

after_deploy:
  - curl https://assertible.com/apis/$SERVICE_ID/run?api_token=$TOKEN

cache:
  directories:
    - node_modules
